version: '4.37.1'

services:
  mysql-pagamentos:
    image: mysql:8.0.29
    container_name: mysql-container-pagamentos
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pagamentos_db
      MYSQL_USER: pagamentos_user
      MYSQL_PASSWORD: pagamentos_password
    volumes:
      - mysql_pagamentos_data:/var/lib/mysql
    restart: "no"

  mysql-pedidos:
    image: mysql:8.0.29
    container_name: mysql-container-pedidos
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pedidos_db
      MYSQL_USER: pedidos_user
      MYSQL_PASSWORD: pedidos_password
    volumes:
      - mysql_pedidos_data:/var/lib/mysql
    restart: "no"

volumes:
  mysql_pagamentos_data:
  mysql_pedidos_data: